server:
  port: 8085

spring:
  application:
    name: video-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/${DB_NAME:oa_system}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:111111}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
