server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${HOSTNAME:eureka-server}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_PASSWORD:}@localhost:8761/eureka/
  server:
    enable-self-preservation: false
