apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oa-system

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 10-eureka-server.yaml
  - 11-gateway.yaml
  - 20-user-service.yaml
  - 21-approval-service.yaml
  - 22-notice-service.yaml
  - 23-video-service.yaml
  - 24-websocket-service.yaml
  - 30-frontend.yaml
  - 40-ingress.yaml
